apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h84h3urju-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/h84h3urju-java-quarkus-gitops